name: waterapp
description: Water reminder overlay
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  overlay_pop_up: ^1.0.6+6
  flutter_foreground_task: ^8.10.4
  permission_handler: ^11.0.0
  device_info_plus: ^10.0.0

flutter:
  uses-material-design: true